VERSION ?= $(shell tr -d '[:space:]' < VERSION)
CODESIGN_IDENTITY ?= Apple Development
EXPECTED_CODESIGN_AUTHORITY_PREFIX ?= Authority=Apple Development:
CODE_SIGN_STYLE ?= Manual
DEVELOPMENT_TEAM ?= W9C2P3N7Q2
RELEASE_DIR ?= .release
RELEASE_TAG ?= v$(VERSION)
APP_INSTALL_DIR ?= /Applications
SPARKLE_PUBLIC_KEY ?= kcc3956V3+Yo8GtwFJ8Odb9sphIr09/9dsuoYBNtxf0=
ARGS ?=

.PHONY: generate xcodeproj build build-clean run run-clean cli check release install installed clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	export XCODEGEN_WINMUX_SPARKLE_PUBLIC_KEY="$(SPARKLE_PUBLIC_KEY)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux .debug && \
	cp -r .build/debug/WinMuxApp .debug'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

run-clean:
	$(MAKE) build-clean VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	config_path="$${WINMUX_CONFIG_PATH:-}"; \
	if [ -n "$$config_path" ]; then \
	    if [ ! -f "$$config_path" ]; then \
	        echo "Missing WinMux config: $$config_path" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$config_path" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

check:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	swift test && \
	python3 -m unittest script/test_validate_appcast.py && \
	swift package resolve && \
	git diff --exit-code -- Package.resolved'

release:
	$(MAKE) xcodeproj VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	test -n "$(VERSION)" && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	archive_path="$$release_dir/$$app_name-$(VERSION).xcarchive"; \
	derived_data_path="$$release_dir/$$app_name-$(VERSION).deriveddata"; \
	app_path="$$archive_path/Products/Applications/$$app_name.app"; \
	zip_path="$$release_dir/$$app_name-$(VERSION).zip"; \
	appcast_path="$$release_dir/appcast.xml"; \
	log_path="$$release_dir/$$app_name-$(VERSION)-xcodebuild.log"; \
	rm -rf "$$archive_path" "$$zip_path" "$$appcast_path" "$$derived_data_path"; \
	mkdir -p "$$release_dir"; \
	xcodebuild-pretty "$$log_path" \
	    -project WinMux.xcodeproj \
	    -scheme WinMux \
	    -configuration Release \
	    -archivePath "$$archive_path" \
	    -derivedDataPath "$$derived_data_path" \
	    CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" \
	    DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" \
	    CODE_SIGN_STYLE="$(CODE_SIGN_STYLE)" \
	    archive; \
	test -d "$$app_path"; \
	test "$$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$$app_path/Contents/Info.plist")" = "$(VERSION)"; \
	test "$$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$$app_path/Contents/Info.plist")" = "$(VERSION)"; \
	codesign --verify --deep --strict --verbose=2 "$$app_path"; \
	codesign -dv --verbose=4 "$$app_path" 2>&1 | grep -F "$(EXPECTED_CODESIGN_AUTHORITY_PREFIX)" >/dev/null; \
	codesign -dv --verbose=4 "$$app_path" 2>&1 | grep -E "^CodeDirectory .*flags=.*runtime" >/dev/null; \
	ditto -c -k --sequesterRsrc --keepParent "$$app_path" "$$zip_path"; \
	sparkle_appcast="$$(find "$$derived_data_path/SourcePackages/artifacts" -type f -name generate_appcast -print -quit)"; \
	test -n "$$sparkle_appcast"; \
	appcast_stage="$$(mktemp -d "$$release_dir/appcast-stage.XXXXXX")"; \
	trap "rm -rf \"$$appcast_stage\"" EXIT; \
	cp "$$zip_path" "$$appcast_stage/"; \
	if [ -n "$${SPARKLE_PRIVATE_KEY:-}" ]; then \
	    printf "%s" "$$SPARKLE_PRIVATE_KEY" | "$$sparkle_appcast" --ed-key-file - --download-url-prefix "https://github.com/ZimengXiong/winmux/releases/download/$(RELEASE_TAG)/" "$$appcast_stage"; \
	else \
	    "$$sparkle_appcast" --download-url-prefix "https://github.com/ZimengXiong/winmux/releases/download/$(RELEASE_TAG)/" "$$appcast_stage"; \
	fi; \
	python3 script/validate-appcast.py "$$appcast_stage/appcast.xml" "$(VERSION)" "https://github.com/ZimengXiong/winmux/releases/download/$(RELEASE_TAG)/$$app_name-$(VERSION).zip"; \
	cp "$$appcast_stage/appcast.xml" "$$appcast_path"; \
	test -f "$$appcast_path"'

install:
	$(MAKE) release VERSION="$(VERSION)" CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	app_path="$$release_dir/$$app_name-$(VERSION).xcarchive/Products/Applications/$$app_name.app"; \
	install_dir="$(APP_INSTALL_DIR)"; \
	install_path="$$install_dir/$$app_name.app"; \
	test -d "$$app_path"; \
	mkdir -p "$$install_dir"; \
	osascript -e "tell application \"$$app_name\" to quit" >/dev/null 2>&1 || true; \
	rm -rf "$$install_path"; \
	ditto "$$app_path" "$$install_path"; \
	xattr -dr com.apple.quarantine "$$install_path" >/dev/null 2>&1 || true; \
	open "$$install_path"'

installed: install

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
